export const board = [
    ['a8', 'b8', 'c8', 'd8', 'e8', 'f8', 'g8', 'h8'],
    ['a7', 'b7', 'c7', 'd7', 'e7', 'f7', 'g7', 'h7'],
    ['a6', 'b6', 'c6', 'd6', 'e6', 'f6', 'g6', 'h6'],
    ['a5', 'b5', 'c5', 'd5', 'e5', 'f5', 'g5', 'h5'],
    ['a4', 'b4', 'c4', 'd4', 'e4', 'f4', 'g4', 'h4'],
    ['a3', 'b3', 'c3', 'd3', 'e3', 'f3', 'g3', 'h3'],
    ['a2', 'b2', 'c2', 'd2', 'e2', 'f2', 'g2', 'h2'],
    ['a1', 'b1', 'c1', 'd1', 'e1', 'f1', 'g1', 'h1'],
];

export const initialPiecesLocation = {
    a8: 'black-rook',
    b8: 'black-horse',
    c8: 'black-bishop',
    d8: 'black-queen',
    e8: 'black-king',
    f8: 'black-bishop',
    g8: 'black-horse',
    h8: 'black-rook',
    a7: 'black-pawn',
    b7: 'black-pawn',
    c7: 'black-pawn',
    d7: 'black-pawn',
    e7: 'black-pawn',
    f7: 'black-pawn',
    g7: 'black-pawn',
    h7: 'black-pawn',
    a6: 'empty-square',
    b6: 'empty-square',
    c6: 'empty-square',
    d6: 'empty-square',
    e6: 'empty-square',
    f6: 'empty-square',
    g6: 'empty-square',
    h6: 'empty-square',
    a5: 'empty-square',
    b5: 'empty-square',
    c5: 'empty-square',
    d5: 'empty-square',
    e5: 'empty-square',
    f5: 'empty-square',
    g5: 'empty-square',
    h5: 'empty-square',
    a4: 'empty-square',
    b4: 'empty-square',
    c4: 'empty-square',
    d4: 'empty-square',
    e4: 'empty-square',
    f4: 'empty-square',
    g4: 'empty-square',
    h4: 'empty-square',
    a3: 'empty-square',
    b3: 'empty-square',
    c3: 'empty-square',
    d3: 'empty-square',
    e3: 'empty-square',
    f3: 'empty-square',
    g3: 'empty-square',
    h3: 'empty-square',
    a2: 'white-pawn',
    b2: 'white-pawn',
    c2: 'white-pawn',
    d2: 'white-pawn',
    e2: 'white-pawn',
    f2: 'white-pawn',
    g2: 'white-pawn',
    h2: 'white-pawn',
    a1: 'white-rook',
    b1: 'white-horse',
    c1: 'white-bishop',
    d1: 'white-queen',
    e1: 'white-king',
    f1: 'white-bishop',
    g1: 'white-horse',
    h1: 'white-rook',
};

export const whiteSquares = [
    'a8',
    'c8',
    'e8',
    'g8',
    'b7',
    'd7',
    'f7',
    'h7',
    'a6',
    'c6',
    'e6',
    'g6',
    'b5',
    'd5',
    'f5',
    'h5',
    'a4',
    'c4',
    'e4',
    'g4',
    'b3',
    'd3',
    'f3',
    'h3',
    'a2',
    'c2',
    'e2',
    'g2',
    'b1',
    'd1',
    'f1',
    'h1',
];

export const whitePieces = [
    'white-pawn',
    'white-rook',
    'white-horse',
    'white-bishop',
    'white-queen',
    'white-king',
    'white-bishop',
    'white-horse',
    'white-rook',
];

export const blackPieces = [
    'black-pawn',
    'black-rook',
    'black-horse',
    'black-bishop',
    'black-queen',
    'black-king',
    'black-bishop',
    'black-horse',
    'black-rook',
];
